/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomizationRouteImport } from './routes/customization'
import { Route as ExportMarketsRouteImport } from './routes/export-markets'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as CategoryCategorySubcategoryRouteImport } from './routes/category/$category/$subcategory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizationRoute = CustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportMarketsRoute = ExportMarketsRouteImport.update({
  id: '/export-markets',
  path: '/export-markets',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySubcategoryRoute =
  CategoryCategorySubcategoryRouteImport.update({
    id: '/category/$category/$subcategory',
    path: '/category/$category/$subcategory',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customization': typeof CustomizationRoute
  '/export-markets': typeof ExportMarketsRoute
  '/faq': typeof FaqRoute
  '/manufacturing': typeof ManufacturingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/category/$category/$subcategory': typeof CategoryCategorySubcategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customization': typeof CustomizationRoute
  '/export-markets': typeof ExportMarketsRoute
  '/faq': typeof FaqRoute
  '/manufacturing': typeof ManufacturingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/products': typeof ProductsIndexRoute
  '/category/$category/$subcategory': typeof CategoryCategorySubcategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customization': typeof CustomizationRoute
  '/export-markets': typeof ExportMarketsRoute
  '/faq': typeof FaqRoute
  '/manufacturing': typeof ManufacturingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/category/$category/$subcategory': typeof CategoryCategorySubcategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/customization'
    | '/export-markets'
    | '/faq'
    | '/manufacturing'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/blog/$slug'
    | '/category/$slug'
    | '/products/$slug'
    | '/blog/'
    | '/products/'
    | '/category/$category/$subcategory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/customization'
    | '/export-markets'
    | '/faq'
    | '/manufacturing'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/blog/$slug'
    | '/category/$slug'
    | '/products/$slug'
    | '/blog'
    | '/products'
    | '/category/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/customization'
    | '/export-markets'
    | '/faq'
    | '/manufacturing'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/blog/$slug'
    | '/category/$slug'
    | '/products/$slug'
    | '/blog/'
    | '/products/'
    | '/category/$category/$subcategory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CustomizationRoute: typeof CustomizationRoute
  ExportMarketsRoute: typeof ExportMarketsRoute
  FaqRoute: typeof FaqRoute
  ManufacturingRoute: typeof ManufacturingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  CategoryCategorySubcategoryRoute: typeof CategoryCategorySubcategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customization': {
      id: '/customization'
      path: '/customization'
      fullPath: '/customization'
      preLoaderRoute: typeof CustomizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-markets': {
      id: '/export-markets'
      path: '/export-markets'
      fullPath: '/export-markets'
      preLoaderRoute: typeof ExportMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category/$subcategory': {
      id: '/category/$category/$subcategory'
      path: '/category/$category/$subcategory'
      fullPath: '/category/$category/$subcategory'
      preLoaderRoute: typeof CategoryCategorySubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CustomizationRoute: CustomizationRoute,
  ExportMarketsRoute: ExportMarketsRoute,
  FaqRoute: FaqRoute,
  ManufacturingRoute: ManufacturingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  CategoryCategorySubcategoryRoute: CategoryCategorySubcategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
